default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root1234
  host: localhost
  port: 3306
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  host: localhost
  username: root
  password: root1234
  database: myapp_development
  database: myapp_development
  socket: /var/run/mysqld/mysqld.sock
test:
  <<: *default
  database: myapp_test

production:
  primary: &primary_production
    <<: *default
    database: myapp_production
    username: myapp
    password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: myapp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: myapp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: myapp_production_cable
    migrations_paths: db/cable_migrate
